// <auto-generated />
namespace BlogProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddTriggers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTriggers));
        
        string IMigrationMetadata.Id
        {
            get { return "202601071711475_AddTriggers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
